using System;
using System.Collections.Generic;

namespace Fasciculus.Algorithms.Fuzzy
{
    /// <summary>
    /// A fuzzy bytes entry returned from the <see cref="FuzzyBytesGenerator"/>.
    /// </summary>
    public class FuzzyBytes
    {
        /// <summary>
        /// The generated bytes.
        /// </summary>
        public byte[] Bytes { get; }

        /// <summary>
        /// The edit distance from the start array given to the generator.
        /// </summary>
        public int Distance { get; }

        /// <summary>
        /// Initializes a new instance of this entry.
        /// </summary>
        public FuzzyBytes(byte[] bytes, int distance)
        {
            Bytes = bytes;
            Distance = distance;
        }

        /// <summary>
        /// Generates fuzzy bytes from the given start value.
        /// </summary>
        public static IEnumerable<FuzzyBytes> Generate(ReadOnlySpan<byte> start, int maxDistance)
            => FuzzyBytesGenerator.Generate(start, maxDistance);
    }
}
