using System.Collections.Generic;

namespace Fasciculus.NuGet.Services
{
    public class IgnoredPackages : IIgnoredPackages
    {
        private readonly SortedSet<string> ignored = [];

        public IgnoredPackages()
        {
            ignored.Add("Microsoft.CSharp");
            ignored.Add("Microsoft.VisualBasic.Core");
            ignored.Add("Microsoft.VisualBasic");
            ignored.Add("Microsoft.Win32.Primitives");
            ignored.Add("Microsoft.Win32.Registry");
            ignored.Add("mscorlib");
            ignored.Add("netstandard");
            ignored.Add("System.AppContext");
            ignored.Add("System.Buffers");
            ignored.Add("System.Collections.Concurrent");
            ignored.Add("System.Collections");
            ignored.Add("System.Collections.Immutable");
            ignored.Add("System.Collections.NonGeneric");
            ignored.Add("System.Collections.Specialized");
            ignored.Add("System.ComponentModel.Annotations");
            ignored.Add("System.ComponentModel.DataAnnotations");
            ignored.Add("System.ComponentModel");
            ignored.Add("System.ComponentModel.EventBasedAsync");
            ignored.Add("System.ComponentModel.Primitives");
            ignored.Add("System.ComponentModel.TypeConverter");
            ignored.Add("System.Configuration");
            ignored.Add("System.Console");
            ignored.Add("System.Core");
            ignored.Add("System.Data.Common");
            ignored.Add("System.Data.DataSetExtensions");
            ignored.Add("System.Data");
            ignored.Add("System.Diagnostics.Contracts");
            ignored.Add("System.Diagnostics.Debug");
            ignored.Add("System.Diagnostics.DiagnosticSource");
            ignored.Add("System.Diagnostics.FileVersionInfo");
            ignored.Add("System.Diagnostics.Process");
            ignored.Add("System.Diagnostics.StackTrace");
            ignored.Add("System.Diagnostics.TextWriterTraceListener");
            ignored.Add("System.Diagnostics.Tools");
            ignored.Add("System.Diagnostics.TraceSource");
            ignored.Add("System.Diagnostics.Tracing");
            ignored.Add("System");
            ignored.Add("System.Drawing");
            ignored.Add("System.Drawing.Primitives");
            ignored.Add("System.Dynamic.Runtime");
            ignored.Add("System.Formats.Asn1");
            ignored.Add("System.Formats.Tar");
            ignored.Add("System.Globalization.Calendars");
            ignored.Add("System.Globalization");
            ignored.Add("System.Globalization.Extensions");
            ignored.Add("System.IO.Compression.Brotli");
            ignored.Add("System.IO.Compression");
            ignored.Add("System.IO.Compression.FileSystem");
            ignored.Add("System.IO.Compression.ZipFile");
            ignored.Add("System.IO");
            ignored.Add("System.IO.FileSystem.AccessControl");
            ignored.Add("System.IO.FileSystem");
            ignored.Add("System.IO.FileSystem.DriveInfo");
            ignored.Add("System.IO.FileSystem.Primitives");
            ignored.Add("System.IO.FileSystem.Watcher");
            ignored.Add("System.IO.IsolatedStorage");
            ignored.Add("System.IO.MemoryMappedFiles");
            ignored.Add("System.IO.Pipelines");
            ignored.Add("System.IO.Pipes.AccessControl");
            ignored.Add("System.IO.Pipes");
            ignored.Add("System.IO.UnmanagedMemoryStream");
            ignored.Add("System.Linq");
            ignored.Add("System.Linq.Expressions");
            ignored.Add("System.Linq.Parallel");
            ignored.Add("System.Linq.Queryable");
            ignored.Add("System.Memory");
            ignored.Add("System.Net");
            ignored.Add("System.Net.Http");
            ignored.Add("System.Net.Http.Json");
            ignored.Add("System.Net.HttpListener");
            ignored.Add("System.Net.Mail");
            ignored.Add("System.Net.NameResolution");
            ignored.Add("System.Net.NetworkInformation");
            ignored.Add("System.Net.Ping");
            ignored.Add("System.Net.Primitives");
            ignored.Add("System.Net.Quic");
            ignored.Add("System.Net.Requests");
            ignored.Add("System.Net.Security");
            ignored.Add("System.Net.ServicePoint");
            ignored.Add("System.Net.Sockets");
            ignored.Add("System.Net.WebClient");
            ignored.Add("System.Net.WebHeaderCollection");
            ignored.Add("System.Net.WebProxy");
            ignored.Add("System.Net.WebSockets.Client");
            ignored.Add("System.Net.WebSockets");
            ignored.Add("System.Numerics");
            ignored.Add("System.Numerics.Vectors");
            ignored.Add("System.ObjectModel");
            ignored.Add("System.Reflection.DispatchProxy");
            ignored.Add("System.Reflection");
            ignored.Add("System.Reflection.Emit");
            ignored.Add("System.Reflection.Emit.ILGeneration");
            ignored.Add("System.Reflection.Emit.Lightweight");
            ignored.Add("System.Reflection.Extensions");
            ignored.Add("System.Reflection.Metadata");
            ignored.Add("System.Reflection.Primitives");
            ignored.Add("System.Reflection.TypeExtensions");
            ignored.Add("System.Resources.Reader");
            ignored.Add("System.Resources.ResourceManager");
            ignored.Add("System.Resources.Writer");
            ignored.Add("System.Runtime.CompilerServices.Unsafe");
            ignored.Add("System.Runtime.CompilerServices.VisualC");
            ignored.Add("System.Runtime");
            ignored.Add("System.Runtime.Extensions");
            ignored.Add("System.Runtime.Handles");
            ignored.Add("System.Runtime.InteropServices");
            ignored.Add("System.Runtime.InteropServices.JavaScript");
            ignored.Add("System.Runtime.InteropServices.RuntimeInformation");
            ignored.Add("System.Runtime.Intrinsics");
            ignored.Add("System.Runtime.Loader");
            ignored.Add("System.Runtime.Numerics");
            ignored.Add("System.Runtime.Serialization");
            ignored.Add("System.Runtime.Serialization.Formatters");
            ignored.Add("System.Runtime.Serialization.Json");
            ignored.Add("System.Runtime.Serialization.Primitives");
            ignored.Add("System.Runtime.Serialization.Xml");
            ignored.Add("System.Security.AccessControl");
            ignored.Add("System.Security.Claims");
            ignored.Add("System.Security.Cryptography.Algorithms");
            ignored.Add("System.Security.Cryptography.Cng");
            ignored.Add("System.Security.Cryptography.Csp");
            ignored.Add("System.Security.Cryptography");
            ignored.Add("System.Security.Cryptography.Encoding");
            ignored.Add("System.Security.Cryptography.OpenSsl");
            ignored.Add("System.Security.Cryptography.Primitives");
            ignored.Add("System.Security.Cryptography.X509Certificates");
            ignored.Add("System.Security");
            ignored.Add("System.Security.Principal");
            ignored.Add("System.Security.Principal.Windows");
            ignored.Add("System.Security.SecureString");
            ignored.Add("System.ServiceModel.Web");
            ignored.Add("System.ServiceProcess");
            ignored.Add("System.Text.Encoding.CodePages");
            ignored.Add("System.Text.Encoding");
            ignored.Add("System.Text.Encoding.Extensions");
            ignored.Add("System.Text.Encodings.Web");
            ignored.Add("System.Text.Json");
            ignored.Add("System.Text.RegularExpressions");
            ignored.Add("System.Threading.Channels");
            ignored.Add("System.Threading");
            ignored.Add("System.Threading.Overlapped");
            ignored.Add("System.Threading.Tasks.Dataflow");
            ignored.Add("System.Threading.Tasks");
            ignored.Add("System.Threading.Tasks.Extensions");
            ignored.Add("System.Threading.Tasks.Parallel");
            ignored.Add("System.Threading.Thread");
            ignored.Add("System.Threading.ThreadPool");
            ignored.Add("System.Threading.Timer");
            ignored.Add("System.Transactions");
            ignored.Add("System.Transactions.Local");
            ignored.Add("System.ValueTuple");
            ignored.Add("System.Web");
            ignored.Add("System.Web.HttpUtility");
            ignored.Add("System.Windows");
            ignored.Add("System.Xml");
            ignored.Add("System.Xml.Linq");
            ignored.Add("System.Xml.ReaderWriter");
            ignored.Add("System.Xml.Serialization");
            ignored.Add("System.Xml.XDocument");
            ignored.Add("System.Xml.XmlDocument");
            ignored.Add("System.Xml.XmlSerializer");
            ignored.Add("System.Xml.XPath");
            ignored.Add("System.Xml.XPath.XDocument");
            ignored.Add("WindowsBase");
        }

        public bool IsIgnored(string packageId)
        {
            if (packageId.StartsWith("runtime."))
            {
                return true;
            }

            return ignored.Contains(packageId);
        }
    }
}
